### PR TITLE
Fixed other images than products appear in lightgallery.

### PR DESCRIPTION
**Pull request by LucaPipolo**
More information on the [Asana task](https://app.asana.com/0/233352750834854/539844171874466/f).

This was happening because, on some themes, inside `.woocommerce-product-gallery` some other elements can exists (e.g. added by JS). Checking for `.woocommerce-product-gallery__wrapper` we can be more specific and avoid that type of conflict that generates missing images.

### CODE REVIEW

**Comment by fabianmarz** [comment]
Instead of changing the calling element selector you should rather check the "root" of the cause. This happens because super generic `a` selector introduced here:  https://github.com/netzstrategen/wordpress-gallerya/commit/0766b4f00e63e350a02c3c2f89169b265218cbd0. Also, the selector was changed again some time before.

Is there a possibility to specify the selector to actual WooCommerce gallery images only rather selecting all containing `a` tags? I see there is a `.woocommerce-product-gallery__image`. Is this a custom template class, or is this coming from the official WooCommerce templates? If this is custom, we can also consider of using a filterable value. For now, I'm fine with adjusting the selector accordingly and put a filterable value on hold.

**Comment by LucaPipolo** [comment]
@fabianmarz, yep: we can adjust also the selector to be `.woocommerce-product-gallery__image > a`. Are you fine with this solution? Looks better?

**Comment by sun** [comment]
Gallerya is not only used for WooCommerce product images.  This is why we moved the condition to the primary/wrapping selector.

**Comment by fabianmarz** [comment]
We introduced [support](https://github.com/netzstrategen/wordpress-gallerya/commit/95f465d6cedeb495b339f10c411fb8d57b25e361) for the WooCommerce gallery two years ago. So the selector for [this](https://github.com/netzstrategen/wordpress-gallerya/blob/bb6cd9c2cc7a7bc862a32e5b5ff3e71d2a2ccc7e/assets/scripts/script.js#L49) codeblock is actually used for WooCommerce images only.

**Comment by sun** [comment]
I almost wanted to approve this PR, but double-checking the markup once again, I noticed that there is not actually a difference with this change, as there is no other markup between the two elements/classes:
https://github.com/woocommerce/woocommerce/blob/6e08ff0284c95883154988b675c6c169caf695c9/templates/single-product/product-image.php#L30-L37

**Comment by LucaPipolo** [comment]
Some themes, e.g. KHC one, are adding, using JS, some extra markup to the `.woocommerce-product-gallery` selector. This added markup (used to generate/style thumbnails) let Gallerya include in the lightbox also some elements that should be not included.

Instead, inside `.woocommerce-product-gallery__image`, no extra markup is added by anything else so we're sure that inside there are only needed images and nothing else.

**Comment by fabianmarz** [comment]
We should adjust the selector still, as `a` is very generic and not really indicates the use of an image. Instead using `.woocommerce-product-gallery__image` or maybe `[class*=image]`.

**Comment by LucaPipolo** [comment]
Yeah, still agree with you, Fabian. 👍

**Comment by sun** [comment]
@LucaPipolo Are you going to follow up with a more specific selector for the items/slides?

**Pull request merged**
