### PR TITLE
Fixed images are not visible on mobile.

### PR DESCRIPTION
**Pull request by fabianmarz**
**Problem:**
- On screens `<768px` the images are not visible as the `margin: auto` values push the element to a zero width.

**Proposed solution**
- Apply the `margin: auto` for `>=768px` screens.

### CODE REVIEW

**Comment by colourgarden** [comment]
@fabianmarz As discussed, I adjusted the vertical margins on mobile as there was a lot of whitespace. Otherwise, your changes are ok.

However, there was an additional problem with the build process because the version of `gulp-sass` we're using is old and has apparently been changed/removed. So I bumped the `gulp-sass` version which returned a few minor diffs.

One thing worth pointing out is that there looks like some additional social icons in the icon font file. Were these missing before?

**Comment by fabianmarz** [comment]
I don't know about the font files and why they were added from your build process. I think we can proceed with this as the icons should be in the [font](https://github.com/sachinchoolur/lightGallery/commit/be7573e4ded59fc1a4a1136ba89eae227e8f21ab#diff-25854b93b81b87168dd31d844864e7a7R43) since ages. Maybe there's an option to exclude the social media plugin in the build process?

**Comment by LucaPipolo** [comment]
@colourgarden + @fabianmarz — since we're going to push this to WordPress.org, please pay attention to update as well the `README.txt` version. Thanks!

**Comment by fabianmarz** [comment]
@LucaPipolo, can you please review so we can merge this ASAP?

**Comment by fabianmarz** [comment]
@LucaPipolo, no, they are not related. @colourgarden added them as he updated the sass version which resulted in a few minor changes as he noted in his comment above.

**Pull request merged**
